export type ExplainerFormat = "video" | "article" | "visualization" | "artifact" | "animation" | "deck";

export interface ExplainerIdea {
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  playlist: string;
  formats: ExplainerFormat[];
  duration: string;
  hook: string;
  artifact: string;
  difficulty: "quick" | "standard" | "deep";
  status: "idea";
}

export const EXPLAINER_IDEAS: ExplainerIdea[] = [
  { slug: "serverless-vs-serverful", title: "Serverless vs Serverful: What Actually Changes?", description: "Compare always-on servers, functions, cold starts, scaling, state, pricing, and the workloads that fit each model.", category: "Cloud & Infrastructure", tags: ["cloud","serverless","backend","architecture","scaling"], playlist: "Architecture in 10 Minutes", formats: ["video","article","visualization","deck"], duration: "8–10 min", hook: "Take the same API from one VM to serverless and watch every trade-off appear.", artifact: "Interactive request-cost + latency playground.", difficulty: "standard", status: "idea" },
  { slug: "cookies-localstorage-indexeddb", title: "Cookies vs localStorage vs IndexedDB: Where Should Data Live?", description: "A visual browser-storage guide covering size, security, lifetime, synchronous APIs, offline use, and server visibility.", category: "Web Foundations", tags: ["web","browser","storage","security","frontend"], playlist: "Browser Mechanics", formats: ["video","article","visualization"], duration: "6–8 min", hook: "Follow one piece of user data as it moves from a cookie to IndexedDB.", artifact: "Browser storage decision tree.", difficulty: "quick", status: "idea" },
  { slug: "jwt-vs-sessions", title: "JWT vs Sessions vs Opaque Tokens", description: "Demystify authentication state, token storage, revocation, rotation, cookies, and why stateless auth still has state somewhere.", category: "Security", tags: ["security","auth","jwt","sessions","web"], playlist: "Security in Plain English", formats: ["video","article","visualization","deck"], duration: "9–12 min", hook: "Draw the exact database and request flow behind three common login designs.", artifact: "Auth-flow simulator with revoke/rotate controls.", difficulty: "standard", status: "idea" },
  { slug: "cors-actually-explained", title: "CORS: Why Your Browser Says Blocked by Policy", description: "Explain origins, preflights, simple requests, credentials, headers, and why CORS is a browser rule—not a server firewall.", category: "Web Protocols", tags: ["web","cors","http","security","browser"], playlist: "Web Mechanics", formats: ["video","article","animation"], duration: "5–7 min", hook: "Animate one fetch request and show exactly where the browser stops it.", artifact: "Live CORS header playground.", difficulty: "quick", status: "idea" },
  { slug: "webhooks-polling-sse-websockets", title: "Webhooks vs Polling vs SSE vs WebSockets", description: "A practical decision guide for pushing data: latency, directionality, infrastructure, retries, reconnection, and use cases.", category: "Backend Engineering", tags: ["backend","realtime","webhooks","sse","websockets"], playlist: "Backend Systems in Motion", formats: ["video","article","visualization","deck"], duration: "8–11 min", hook: "Use the same notification product and swap its transport four ways.", artifact: "Realtime transport simulator.", difficulty: "standard", status: "idea" },
  { slug: "browser-rendering-pipeline", title: "What the Browser Does After HTML Arrives", description: "Trace DOM, CSSOM, render tree, layout, paint, compositing, fonts, JavaScript, and frames.", category: "Frontend", tags: ["browser","frontend","rendering","performance","javascript"], playlist: "Browser Mechanics", formats: ["video","article","animation","visualization"], duration: "10–12 min", hook: "Animate one HTML file through every stage until a pixel appears on screen.", artifact: "Frame-by-frame rendering pipeline timeline.", difficulty: "deep", status: "idea" },
  { slug: "javascript-event-loop", title: "JavaScript Event Loop: One Click, Five Queues", description: "Make the call stack, microtasks, timers, rendering, and async callbacks visible with a tiny runnable example.", category: "JavaScript", tags: ["javascript","async","event-loop","performance","frontend"], playlist: "JavaScript, Visually", formats: ["video","article","animation","artifact"], duration: "7–9 min", hook: "Predict the console output before pressing play, then let the simulator prove it.", artifact: "Step-through event-loop playground.", difficulty: "standard", status: "idea" },
  { slug: "tcp-vs-quic", title: "TCP vs QUIC: Why HTTP/3 Changed the Transport Layer", description: "Explain streams, connection setup, head-of-line blocking, TLS integration, loss recovery, and migration.", category: "Networking", tags: ["networking","tcp","quic","http3","performance"], playlist: "Networks, Visually", formats: ["video","article","visualization","deck"], duration: "9–12 min", hook: "Animate packet loss on HTTP/2 and HTTP/3 side by side.", artifact: "Packet timeline comparing TCP and QUIC.", difficulty: "standard", status: "idea" },
  { slug: "load-balancer-algorithms", title: "How Load Balancers Choose Your Server", description: "Round robin, least connections, weighted routing, hashing, health checks, draining, and sticky sessions in one visual story.", category: "System Design", tags: ["system-design","load-balancing","scaling","networking","backend"], playlist: "Distributed Systems, Visualized", formats: ["video","article","visualization"], duration: "7–10 min", hook: "Send 100 requests through the same fleet and watch each algorithm distribute them.", artifact: "Interactive load-balancer playground.", difficulty: "standard", status: "idea" },
  { slug: "consistent-hashing-explained", title: "Consistent Hashing: The Ring That Saves Your Cache", description: "Show why naive modulo hashing causes churn and how virtual nodes reduce remapping when servers change.", category: "Distributed Systems", tags: ["distributed-systems","consistent-hashing","caching","scaling"], playlist: "Distributed Systems, Visualized", formats: ["video","article","visualization","animation"], duration: "8–10 min", hook: "Kill one server mid-request and watch which keys actually move.", artifact: "Drag-and-drop hashing ring.", difficulty: "standard", status: "idea" },
  { slug: "database-replication", title: "Database Replication: What Your Read Replica Really Knows", description: "Explain primary/replica flow, write-ahead logs, lag, failover, read-after-write consistency, and stale reads.", category: "Databases", tags: ["databases","replication","postgresql","consistency","backend"], playlist: "Data Systems, Inside Out", formats: ["video","article","visualization","deck"], duration: "9–12 min", hook: "Write a row, read it immediately, and see why the answer can still be old.", artifact: "Replica lag timeline simulator.", difficulty: "deep", status: "idea" },
  { slug: "database-isolation-levels", title: "Database Transactions & Isolation Levels, Visually", description: "Make dirty reads, non-repeatable reads, phantom reads, locks, snapshots, and serializability concrete.", category: "Databases", tags: ["databases","transactions","sql","concurrency","consistency"], playlist: "Data Systems, Inside Out", formats: ["video","article","animation","deck"], duration: "10–14 min", hook: "Run two transactions at once and watch anomalies appear or disappear.", artifact: "Two-transaction concurrency simulator.", difficulty: "deep", status: "idea" },
  { slug: "btree-vs-lsm-tree", title: "B-Tree vs LSM-Tree: Two Ways to Build Fast Storage", description: "Compare random writes, sequential writes, compaction, read amplification, and why databases choose different storage engines.", category: "Databases", tags: ["databases","btree","lsm-tree","storage","performance"], playlist: "Data Systems, Inside Out", formats: ["video","article","visualization"], duration: "9–12 min", hook: "Plot where every write goes in a B-tree and an LSM-tree.", artifact: "Write/read amplification visualizer.", difficulty: "deep", status: "idea" },
  { slug: "bloom-filters", title: "Bloom Filters: The Tiny Bit Array That Says Probably", description: "Explain probabilistic membership, hash functions, false positives, memory savings, and real database/cache use cases.", category: "Data Structures", tags: ["algorithms","data-structures","bloom-filters","databases","performance"], playlist: "Data Structures, Inside Out", formats: ["video","article","animation","visualization"], duration: "6–8 min", hook: "Watch one false positive form bit by bit.", artifact: "Interactive Bloom-filter playground.", difficulty: "quick", status: "idea" },
  { slug: "inverted-index-vs-vector-search", title: "Inverted Index vs Vector Search: How Search Finds Things", description: "Contrast lexical retrieval, inverted indexes, embeddings, vector similarity, hybrid search, and when each wins.", category: "AI & Search", tags: ["ai","search","information-retrieval","vectors","embeddings"], playlist: "AI Systems, Demystified", formats: ["video","article","visualization","deck"], duration: "9–12 min", hook: "Search the same query with keywords and vectors and compare the retrieved evidence.", artifact: "Hybrid-search explorer.", difficulty: "standard", status: "idea" },
  { slug: "rag-under-the-hood", title: "RAG Under the Hood: What Happens Between Question and Answer?", description: "Trace chunking, embeddings, retrieval, reranking, context assembly, generation, citations, and evaluation.", category: "Artificial Intelligence", tags: ["ai","rag","llms","embeddings","retrieval"], playlist: "AI Systems, Demystified", formats: ["video","article","visualization","animation","deck"], duration: "10–14 min", hook: "Follow one user question as it becomes five chunks, a context window, and a cited answer.", artifact: "RAG pipeline stepper with retrieval controls.", difficulty: "deep", status: "idea" },
  { slug: "llm-streaming-tokens", title: "How LLM Token Streaming Feels Instant", description: "Explain token generation, HTTP streaming, SSE, buffering, flushes, backpressure, and what the UI actually receives.", category: "AI Engineering", tags: ["ai","llms","streaming","sse","web"], playlist: "AI Systems, Demystified", formats: ["video","article","animation"], duration: "6–9 min", hook: "Zoom from a model token to the exact browser paint that displays it.", artifact: "Token-to-pixel latency timeline.", difficulty: "standard", status: "idea" },
  { slug: "rate-limiting-algorithms", title: "Rate Limiting: Token Bucket vs Leaky Bucket vs Fixed Window", description: "Visualize bursts, fairness, smoothing, distributed counters, and the hidden edge cases of rate limiting.", category: "Backend Engineering", tags: ["backend","rate-limiting","redis","distributed-systems","security"], playlist: "Backend Systems in Motion", formats: ["video","article","visualization","artifact"], duration: "7–9 min", hook: "Throw a burst of 500 requests at three algorithms and compare the shape of the output.", artifact: "Live rate-limit simulator with traffic generator.", difficulty: "standard", status: "idea" },
  { slug: "retries-backoff-jitter", title: "Retries, Exponential Backoff, and Jitter: When Reliability Makes Things Worse", description: "Show retry storms, synchronized clients, backoff curves, jitter strategies, idempotency, and safe retry budgets.", category: "Reliability", tags: ["reliability","backend","retries","distributed-systems","performance"], playlist: "Systems Under Failure", formats: ["video","article","visualization","animation"], duration: "8–11 min", hook: "Make 10,000 clients retry together and watch the outage amplify itself.", artifact: "Retry-storm simulator with jitter controls.", difficulty: "deep", status: "idea" },
  { slug: "password-hashing", title: "Why Passwords Are Hashed: Salts, Peppers, and Slow Hashes", description: "Explain password storage without hand-waving: one-way functions, salts, work factors, memory hardness, and breach economics.", category: "Security", tags: ["security","passwords","cryptography","authentication"], playlist: "Security in Plain English", formats: ["video","article","visualization","deck"], duration: "7–9 min", hook: "Start with a leaked database and show why a salt changes the attacker’s job.", artifact: "Password-cracking cost visualizer.", difficulty: "standard", status: "idea" }
];
